In [1]:
import pandas as pd

df = pd.read_csv("optimizer_results.csv")

df.head()

,ATM_ID,Date,Total_Withdrawals,Total_Deposits,Holiday_Flag,Special_Event_Flag,Previous_Day_Cash_Level,Nearby_Competitor_ATMs,Cash_Demand_Next_Day,Year,...,Weather_Condition_Snowy,Predicted_Demand,Safety_Buffer_Percentage,Current_Cash_Level,Cash_Shortage,Safety_Buffer_Amount,Required_Cash,Recommended_Refill,Risk_Level,Priority_Rank
0,ATM_0041,2022-04-25,57450,9308,0,0,112953,5,44165,2022,...,False,50164.0,0.15,64811,0,7525.0,57689.0,0.0,Low Risk,3952.5
1,ATM_0007,2023-11-24,72845,17896,0,0,115348,0,41249,2023,...,False,58832.0,0.15,60399,0,8825.0,67657.0,7258.0,Low Risk,1870.0
2,ATM_0014,2022-08-27,42957,12712,0,0,90731,1,29901,2022,...,False,33149.0,0.15,60486,0,4972.0,38122.0,0.0,Low Risk,3952.5
3,ATM_0029,2023-08-27,43014,1375,0,0,88754,5,44155,2023,...,False,42612.0,0.15,47115,0,6392.0,49003.0,1888.0,Low Risk,2135.5
4,ATM_0028,2022-12-15,36379,2938,0,0,129312,0,29784,2022,...,True,34181.0,0.15,95871,0,5127.0,39308.0,0.0,Low Risk,3952.5

In [2]:
import numpy as np

np.random.seed(42)

df["Latitude"] = np.random.uniform(
    18.40, 18.80, len(df)
)

df["Longitude"] = np.random.uniform(
    73.70, 74.10, len(df)
)

In [4]:
top_atms = (
    df.sort_values("Priority_Rank")
      .drop_duplicates(subset="ATM_ID")
      .head(10)
      .reset_index(drop=True)
)

top_atms[
    [
        "ATM_ID",
        "Recommended_Refill",
        "Risk_Level",
        "Priority_Rank"
    ]
]

     ATM_ID  Recommended_Refill Risk_Level  Priority_Rank
0  ATM_0015            133470.0  High Risk            1.0
1  ATM_0009            112652.0  High Risk            2.0
2  ATM_0021            107398.0  High Risk            3.0
3  ATM_0040            100450.0  High Risk            4.0
4  ATM_0019             99206.0  High Risk            5.0
5  ATM_0032             98004.0  High Risk            6.0
6  ATM_0023             97600.0  High Risk            7.0
7  ATM_0031             95512.0  High Risk            8.0
8  ATM_0044             95135.0  High Risk           10.0
9  ATM_0033             95054.0  High Risk           11.0

In [5]:
import numpy as np

np.random.seed(42)

top_atms["Latitude"] = np.random.uniform(
    18.40, 18.80, len(top_atms)
)

top_atms["Longitude"] = np.random.uniform(
    73.70, 74.10, len(top_atms)
)

top_atms[
    [
        "ATM_ID",
        "Latitude",
        "Longitude"
    ]
]

     ATM_ID   Latitude  Longitude
0  ATM_0015  18.549816  73.708234
1  ATM_0009  18.780286  74.087964
2  ATM_0021  18.692798  74.032977
3  ATM_0040  18.639463  73.784936
4  ATM_0019  18.462407  73.772730
5  ATM_0032  18.462398  73.773362
6  ATM_0023  18.423233  73.821697
7  ATM_0031  18.746470  73.909903
8  ATM_0044  18.640446  73.872778
9  ATM_0033  18.683229  73.816492

In [6]:
from scipy.spatial.distance import cdist
import pandas as pd

# Create coordinate array
coordinates = top_atms[["Latitude", "Longitude"]].values

# Compute distance matrix
distance_matrix = cdist(
    coordinates,
    coordinates,
    metric="euclidean"
)

# Convert to DataFrame for readability
distance_df = pd.DataFrame(
    distance_matrix,
    index=top_atms["ATM_ID"],
    columns=top_atms["ATM_ID"]
)

distance_df.round(2)

ATM_ID,ATM_0015,ATM_0009,ATM_0021,ATM_0040,ATM_0019,ATM_0032,ATM_0023,ATM_0031,ATM_0044,ATM_0033
ATM_ID,,,,,,,,,,
ATM_0015,0.00,0.44,0.35,0.12,0.11,0.11,0.17,0.28,0.19,0.17
ATM_0009,0.44,0.00,0.10,0.33,0.45,0.45,0.45,0.18,0.26,0.29
ATM_0021,0.35,0.10,0.00,0.25,0.35,0.35,0.34,0.13,0.17,0.22
ATM_0040,0.12,0.33,0.25,0.00,0.18,0.18,0.22,0.16,0.09,0.05
ATM_0019,0.11,0.45,0.35,0.18,0.00,0.00,0.06,0.32,0.20,0.23
ATM_0032,0.11,0.45,0.35,0.18,0.00,0.00,0.06,0.32,0.20,0.23
ATM_0023,0.17,0.45,0.34,0.22,0.06,0.06,0.00,0.34,0.22,0.26
ATM_0031,0.28,0.18,0.13,0.16,0.32,0.32,0.34,0.00,0.11,0.11
ATM_0044,0.19,0.26,0.17,0.09,0.20,0.20,0.22,0.11,0.00,0.07
ATM_0033,0.17,0.29,0.22,0.05,0.23,0.23,0.26,0.11,0.07,0.00